name: Create AML Infrastructure and Assets on Azure Workflow

on:
  workflow_dispatch:
    inputs:
      Resource_Group_Location: 
        description: 'Azure Resource Group Location'
        required: true
        type: choice
        options:
        - eastus
        - eastus2
        - centralus
        - westeurope
        - westus2
        - eastasia
      AML_Compute_Instance_Name:
        description: 'AML Compute Instance Name (Unique)'
        type: string
        required: true
      AML_Compute_Instance_Size:
        description: 'AML Compute Instance Size'
        required: true
        type: choice
        options:
          - Standard_DS11_v2
          - Standard_DS3_v2
          - Standard_DS12_v2
          - Standard_F4S_v2
      AML_Data_Asset_Name:
        description: 'Dataset Name'
        type: string
        required: true

env:
  AZURE_PASSWORD: 'psudo$1998'


jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure Login
    # uses: azure/login@v1
      # with:
      #   creds: ${{secrets.AZURE_CREDENTIALS}}
      run: | 
        az login -u ${{ secrets.AZURE_ACCOUNT_ID }}  -p ${{ secrets.AZURE_PASSWORD }}
        az account set --subscription ${{ secrets.Subscription_ID }}
    - name: Create Resource Group
      run: | 
        az group create --name ${{ secrets.RESOURCE_GROUP }} --location ${{ github.event.inputs.Resource_Group_Location }}
    - name: Create AML Workspace
      run: |
        az ml workspace create --workspace-name ${{ secrets.AML_WORKSPACE }} --resource-group ${{ secrets.RESOURCE_GROUP }}
    - name: Create AML Compute Instance
      run: |
        az ml compute create --name ${{ github.event.inputs.AML_Compute_Instance_Name }} --type computeinstance --size ${{ github.event.inputs.AML_Compute_Instance_Size }} --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}
        sleep 240
    - name: Create AML Data Set
      run: |
        az ml data create --name ${{ github.event.inputs.AML_Data_Asset_Name }} --version 1 --path ./production/data/  --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}