name: Manually trigger an Azure Machine Learning job

on:
  workflow_dispatch:
    inputs:
      AZURE_ACCOUNT_ID:
        description: 'Azure Account Mail ID'
        type: string
        required: true
      subscriptionID:
        description: 'Azure Subscription ID'
        type: string
        required: true
      resource_group: 
        description: 'Azure Resource Group'
        type: string
        required: true
      aml_workspace:
        description: 'Azure Machine Learning Workspace'
        type: string
        required: true

env:
  AZURE_PASSWORD: 'psudo$1998'

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
    # uses: azure/login@v1
      # with:
      #   creds: ${{secrets.AZURE_CREDENTIALS}}
      run: | 
        az login -u ${{ github.event.inputs.AZURE_ACCOUNT_ID }}  -p $AZURE_PASSWORD
        az account set --subscription ${{ github.event.inputs.subscriptionID }}
    - name: Run Pipeline Job
      run: | 
        az ml job create --file ./src/job.yml --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.aml_workspace }}
        sleep 120
    - name: Get the Job Name/run ID
      run: |
        JOB_NAME=$(az ml job list --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.aml_workspace }} --query "[0].name" | tr -d '"')
    - name: Register the Model in Registry
      run: |
        az ml model create --name "diabetes-predict-mlflow-model" --type "mlflow_model" \
                   --path "azureml://jobs/$JOB_NAME/outputs/artifacts/model" \
                   --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.aml_workspace }}