name: AML Model Training Workflow

on:
  push:
    branches:
      - 'main'

env:
  AZURE_PASSWORD: 'psudo$1998'

jobs:
  train_model:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
    # uses: azure/login@v1
      # with:
      #   creds: ${{secrets.AZURE_CREDENTIALS}}
      run: | 
        az login -u ${{ secrets.AZURE_ACCOUNT_ID }}  -p $AZURE_PASSWORD
        az account set --subscription ${{ secrets.Subscription_ID }}
    - name: Run Pipeline Job
      run: | 
        az ml job create --file ./src/job.yml --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }}
        sleep 200
    - name: Get Job Run ID and Resgister the Model 
      run: |
        RUN_ID=$(az ml job list --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }} --query "[0].name" | tr -d '"')
        az ml model create --name "diabetes-predict-mlflow-model" --type "mlflow_model" --path runs:/$RUN_ID/model  \
                   --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }}
