name: MLflow Model Deployment Workflow

on:
  workflow_run:
    workflows: ["AML Model Training Workflow"]
    types: [completed]
    branches: [main]

env:
  AZURE_PASSWORD: 'psudo$1998'


jobs:
  on-success:
    name: Model Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
    # uses: azure/login@v1
      # with:
      #   creds: ${{secrets.AZURE_CREDENTIALS}}
      run: | 
        az login -u ${{ secrets.AZURE_ACCOUNT_ID }}  -p $AZURE_PASSWORD
        az account set --subscription ${{ secrets.SUBSCRIPTION_ID }}
    - name: Create MLflow Endpoint
      run: |
        Random_Num=$(( $RANDOM ))
        Model_Endpoint_Name="${{ secrets.MODEL_ENDPOINT }}-${Random_Num}"
        az ml online-endpoint create --name ${Model_Endpoint_Name} --auth-mode key --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }} 
    - name: Create MLflow Model Deployment
      run: |
        Random_Id=$(( $RANDOM ))
        Model_Deployment_Name="${{ secrets.MODEL_DEPLOYMENT }}-${Random_Id}-svc"
        az ml online-deployment create --name "${Model_Deployment_Name}" --file ./model-deployment/mlflow-deployment.yml --endpoint-name ${Model_Endpoint_Name} --resource-group ${{ secrets.RESOURCE_GROUP }} --workspace-name ${{ secrets.AML_WORKSPACE }}
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow AML Model Training was failed. The triggering workflow must be run successfully to run this workflow.'
