name: MLflow Model Deployment Workflow

on:
  workflow_run:
    workflows: ["AML Model Training Workflow"]
    types: [completed]
    branches: [main]

env:
  AZURE_PASSWORD: 'psudo$1998'


jobs:
  on-success:
    name: Model Deployment
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
    # uses: azure/login@v1
      # with:
      #   creds: ${{secrets.AZURE_CREDENTIALS}}
      run: | 
        az login -u ${{ secrets.AZURE_ACCOUNT_ID }}  -p $AZURE_PASSWORD
        az account set --subscription ${{ secrets.Subscription_ID }}
    - name: Create MLflow Endpoint
      run: |
        Check_Endpoint=$(az ml online-endpoint show --name ${{ secrets.Model_Endpoint }} --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }} --query "{Name:name}"  --output tsv)
        if [[ -n "${Check_Endpoint}" ]]; then
            echo "Endpoint with the name ${{ secrets.Model_Endpoint }} already exist. Proceed to create Deployment"
        else
            echo "Creating Endpoint"
            az ml online-endpoint create --name ${{ secrets.Model_Endpoint }} --auth-mode key --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }}
        fi 
    - name: Create MLflow Model Deployment
      run: |
        Check_Deployment=$(az ml online-deployment show --name "${{ secrets.MODEL_DEPLOYMENT }}" --endpoint-name ${{ secrets.Model_Endpoint }}  --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }} --query "{Name:name}"  --output tsv)
        if [[ -n "${Check_Deployment}" ]]; then
            echo " Deleting Deployment: ${Check_Deployment}"
            az ml online-deployment delete --name "${{ secrets.MODEL_DEPLOYMENT }}" --endpoint-name ${{ secrets.Model_Endpoint }} --yes  --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }} 
        else
            echo "Creating Deployment"
            az ml online-deployment create --name "${{ secrets.MODEL_DEPLOYMENT }}" --file ./model-deployment/mlflow-deployment.yml --endpoint-name ${{ secrets.Model_Endpoint }} --resource-group ${{ secrets.Resource_Group }} --workspace-name ${{ secrets.AML_Workspace }}
        fi
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow AML Model Training was failed. The triggering workflow must be run successfully to run this workflow.'
