name: MLflow Model Deployment

on:
  workflow_dispatch:
    inputs:
      AZURE_ACCOUNT_ID:
        description: 'Azure Account Mail ID'
        type: string
        required: true
      subscriptionID:
        description: 'Azure Subscription ID'
        type: string
        required: true
      resource_group: 
        description: 'Azure Resource Group'
        type: string
        required: true
      aml_workspace:
        description: 'Azure Machine Learning Workspace'
        type: string
        required: true

env:
  AZURE_PASSWORD: 'psudo$1998'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@main
    - name: Install az ml extension
      run: az extension add -n ml -y
    - name: Azure login
    # uses: azure/login@v1
      # with:
      #   creds: ${{secrets.AZURE_CREDENTIALS}}
      run: | 
        az login -u ${{ github.event.inputs.AZURE_ACCOUNT_ID }}  -p $AZURE_PASSWORD
        az account set --subscription ${{ github.event.inputs.subscriptionID }}
    - name: Create MLflow Endpoint
      run: | 
        az ml online-endpoint create --file ./model-deployment/create-endpoint.yml --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.aml_workspace }}
    - name: Create MLflow Model Deployment
      run: |
        az ml online-deployment create --file ./model-deployment/mlflow-deployment.yml --endpoint diabetes-predict-mlflow-endpoint --all-traffic --resource-group ${{ github.event.inputs.resource_group }} --workspace-name ${{ github.event.inputs.aml_workspace }}  